RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 1
CHUNK_SIZE: 500
CHUNK_OVERLAP: 250
DATA_PATH: 'mistral/data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'mistral'
MODEL_BIN_PATH: 'mistral/models/mistral-7b-instruct-v0.1.Q2_K.gguf'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
MAX_NEW_TOKENS: 1048
TEMPERATURE: 0.00